/*
 * This Java source file was generated by the Gradle 'init' task.

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
 */
class App {


    public static void main(String[] args) {
        Vehicle vehicleA = new Vehicle("vehicleA", "apple");
        Vehicle vehicleB = new Vehicle("vehicleB", "orange");
        vehicleA.speedup(30);
        vehicleB.speedup(40);
        Car car = new Car("java", "difficult");
        car.speedup(120);
        car.speedup(80);
        Bus bus = new Bus("Citybus", "OOCL");
        bus.speedup(80);
        bus.speedup(90);
        Driver fantsz = new Driver(vehicleA, "fantsz");
        fantsz.speedup(50);
        Driver kate = new Driver(vehicleB, "kate");
        kate.speedup(600);
    }
}

class Bus extends Vehicle{
    public Bus(String name, String brand) {
        super(name, brand);
    }
    @Override
    public void speedup (int increase){
        if (increase < 70){
            super.speedup(increase);
        }
        else{
            System.out.println("You are too fast for bus");
        }
    }
}

class Car extends Vehicle{

    public Car(String name, String brand) {
        super(name, brand);
    }

}

class Driver{

    private final Vehicle vehicle;
    private final String name;


    public Driver(Vehicle vehicle, String name) {
        this.vehicle = vehicle;
        this.name = name;
    }

    public void speedup(int increase){
        vehicle.speedup(increase);
    }

}

class Vehicle {

    private String name;
    private String brand;

    public Vehicle(String name, String brand) {
        this.name = name;
        this.brand = brand;
    }


    public void speedup(int speed) {
        System.out.println("name: " + this.name + " Brand: " + this.brand + " Speedup: " + speed);
    }
}